---
date: "2020-05-01T21:48:51-07:00"
title: "Resume"
author: "Gyeongdeok Seo"
categories: ["R"]
mainfont: NanumGothic
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Info
&nbsp;&nbsp;&nbsp;&nbsp;
이름 : 서경덕 <br>
&nbsp;&nbsp;&nbsp;&nbsp;
사용언어 : R, Python <br>
&nbsp;&nbsp;&nbsp;&nbsp;
이메일 : sgd3565@naver.com

# Education
&nbsp;&nbsp;&nbsp;&nbsp;
김해대청고등학교[2013 - 2015]
<br> &nbsp;&nbsp;&nbsp;&nbsp;
연세대학교 응용통계학과[2016 - ]

# Experience
&nbsp;&nbsp;&nbsp;&nbsp;
경제경영동아리 블루칩(2014년 회장)[2013 - 2014]
<br> &nbsp;&nbsp;&nbsp;&nbsp;
연세대학교 통계학회 ESC(2학기 회장) [2020 - ]
<br> &nbsp;&nbsp;&nbsp;&nbsp;
(주)CC&I research 근무 [2017, 2020]

# Project
&nbsp;&nbsp;&nbsp;&nbsp;
게이미피케이션을 활용한 마케팅 연구[2014]<br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 역할 : 총괄 및 T-test활용 마케팅효과 검정<br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 김해대청고등학교 학술제 최우수상

&nbsp;&nbsp;&nbsp;&nbsp;
연세대학교 송도캠퍼스 내 소음연구[2016]<br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 역할 : 소음측정 및 결과데이터 EDA<br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 연세대학교 RC 창의플랫폼 장려상

&nbsp;&nbsp;&nbsp;&nbsp;
살림의료협동조합 설문지 분석[2017]<br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 역할 : 설문지 통계분석 및 EDA 진행 <br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 봉사활동 

&nbsp;&nbsp;&nbsp;&nbsp;
서울시 수소차 충전소 입지선정 연구[2020]<br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 역할 : 데이터 전처리 및 샤이니 대시보드 구현

&nbsp;&nbsp;&nbsp;&nbsp;
재무제표 데이터를 활용한 부실기업 예측연구[2020] <br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 역할 : 데이터 전처리 <br>
&nbsp;&nbsp;&nbsp;&nbsp;
- NA처리(재무제표 지표활용) 및 LOF와 IsolationForest활용한 Multivariate outlier 관찰

&nbsp;&nbsp;&nbsp;&nbsp;
CIFAT 10 데이터셋을 이용한 CNN hyperparameter tuning[2020] <br>
&nbsp;&nbsp;&nbsp;&nbsp;
- 역할 : 파라미터 서치를 위한 모델링(개인프로젝트)

# 수강과목
&nbsp;&nbsp;&nbsp;&nbsp; 통계학입문<br>
&nbsp;&nbsp;&nbsp;&nbsp; 통계방법론<br>
&nbsp;&nbsp;&nbsp;&nbsp; 미분적분학<br>
&nbsp;&nbsp;&nbsp;&nbsp; 선형대수<br>
&nbsp;&nbsp;&nbsp;&nbsp; 수리통계학(1)<br>
&nbsp;&nbsp;&nbsp;&nbsp; 수리통계학(2)<br>
&nbsp;&nbsp;&nbsp;&nbsp; 컴퓨터자료처리<br>
&nbsp;&nbsp;&nbsp;&nbsp; 회귀분석<br>
&nbsp;&nbsp;&nbsp;&nbsp; 탐색적자료분석<br>
&nbsp;&nbsp;&nbsp;&nbsp; 온라인미디어분석<br>
&nbsp;&nbsp;&nbsp;&nbsp; 데이터마이닝<br>
&nbsp;&nbsp;&nbsp;&nbsp; 딥러닝<br>
&nbsp;&nbsp;&nbsp;&nbsp; 데이터사이언스입문<br>
&nbsp;&nbsp;&nbsp;&nbsp; 데이터사이언스를위한확률과정